import Head from 'next/head'
import { Inter } from 'next/font/google'
import styled from '@emotion/styled'

const inter = Inter({ subsets: ['latin'] })

const styleOne = () => `
  padding: 80px;
  background: #33ccff;
`

const Div = styled.div`
  padding: 32px;
  background: #F00;
  color: #fff;
  ${styleOne}
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Div>
          teste
        </Div>
      </main>
    </>
  )
}
