import Head from 'next/head'


const HeadDefault = ({title}: { title: string }) => {
  let showTitle = `ProjetoStater - ${title}`
  return (
    <Head>
      <title>{showTitle}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
export default HeadDefault